spring:
  application:
    name: stock-provider
  jpa:  #配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
    hibernate:
      ddl-auto: update
  cache:
    type: GENERIC
  autoconfigure:
    exclude: com.crazymaker.l2cache.config.J2CacheAutoConfiguration, com.crazymaker.l2cache.config.J2CacheSpringCacheAutoConfiguration


http:
  connection:
     keepAliveTimeout: 60000


j2cache:
  allow-null-values: true
  cache-clean-mode: active
  config-location: j2cache-dev.properties
  j2CacheConfig:
    serialization: json
  l2-cache-open: true
  open-spring-cache: true

rocketmq:
  name-server: http://${SCAFFOLD_ROCKETMQ_HOSTS:192.168.56.121:9876} #rocketmq服务地址
  producer:
    group: rocketmq_test #自定义的组名称
    send-message-timeout: 3000  #消息发送超时时长


#etcd的地址，如有多个用逗号分隔
etcd:
  server: ${etcdServer:http://cdh1:2379}
#  server: ${etcdServer:http://10.170.161.91:2379｝
#  server: http://open-etcd.jd.com:2000


#### 暴露端点
management:
  endpoints:
    web:
      base-path: "/actuator"  # 配置 Endpoint 的基础路径
      exposure:
        include: '*'  #在yaml 文件属于关键字，所以需要加引号
  health:
    defaults:
      enabled: true
    db:
      enabled: false
    show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
  endpoint:
    prometheus:
        enabled: true



#  boot:
#    admin:
#      context-path: consumer