spring:
  application:
    name: uaa-provider
  jpa:  #配置自动建表：update:没有表新建，有表更新操作,控制台显示建表语句
    hibernate:
      ddl-auto: update

eureka:
  client:
    healthcheck:
      enabled: true   #开启客户端健康检查
  instance:
    lease-renewal-interval-in-seconds: 5  # 续租(心跳)频率，Client 发送心跳给 Eureka 的时间间隔，默认 30 秒
    lease-expiration-duration-in-seconds: 15  #  租约有效期，在该时间内若client未更新租约，将剔除client，默认 90 秒